# Example ESP8266 device with a relay and button
# This demonstrates a basic smart switch configuration

substitutions:
  device_name: example-switch
  friendly_name: "Example Switch"

esphome:
  name: ${device_name}
  platform: ESP8266
  board: esp01_1m

# Import common configurations
<<: !include ../common/wifi.yaml
<<: !include ../common/logger.yaml
<<: !include ../common/api.yaml
<<: !include ../common/ota.yaml

# Binary sensor for physical button
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "${friendly_name} Button"
    on_press:
      - switch.toggle: relay

# Switch for controlling the relay
switch:
  - platform: gpio
    name: "${friendly_name}"
    pin: GPIO12
    id: relay
    icon: "mdi:power-socket"

# Status LED
status_led:
  pin:
    number: GPIO13
    inverted: true
